"""Model-version staleness policy.

Controls whether rollout data generated by older actor weights may be consumed
by the trainer. The first synchronous GRPO version should normally require the
current model version only.
"""


class StalenessPolicy:
    """Check whether a trajectory version is acceptable."""

    def is_acceptable(self, trajectory_version: int, current_version: int) -> bool:
        """Allow only current-version trajectories by default."""
        return trajectory_version == current_version

